easy = ['able', 'acid', 'acre', 'aged', 'aide', 'akin', 'alas', 'ally', 'also', 'alto', 'amid', 'anal', 'anna', 'anti',
        'apex', 'arch', 'area', 'army', 'atom', 'atop', 'aunt', 'aura', 'auto', 'avid', 'away', 'axis', 'baby', 'bach',
        'back', 'bail', 'bait', 'bake', 'bald', 'ball', 'band', 'bang', 'bank', 'bare', 'bark', 'barn', 'base', 'bass',
        'bath', 'bats', 'beam', 'bean', 'bear', 'beat', 'beck', 'beef', 'been', 'beer', 'bell', 'belt', 'bend', 'bent',
        'best', 'beta', 'beth', 'bias', 'bike', 'bill', 'bind', 'bird', 'bite', 'blew', 'bloc', 'blog', 'blow', 'blue',
        'blur', 'boat', 'body', 'boil', 'bold', 'bolt', 'bomb', 'bond', 'bone', 'book', 'boom', 'boon', 'boot', 'bore',
        'born', 'boss', 'both', 'bout', 'bowl', 'brad', 'bred', 'brew', 'brow', 'buck', 'bulb', 'bulk', 'bull', 'bump',
        'burn', 'bury', 'bush', 'bust', 'busy', 'butt', 'buzz', 'cafe', 'cage', 'cake', 'calf', 'call', 'calm', 'came',
        'camp', 'cane', 'cape', 'card', 'care', 'carl', 'carr', 'cart', 'case', 'cash', 'cast', 'cave', 'cell', 'cent',
        'chad', 'chap', 'chat', 'chef', 'chic', 'chin', 'chip', 'chop', 'cite', 'city', 'clad', 'clan', 'clay', 'clip',
        'club', 'clue', 'coal', 'coat', 'coca', 'code', 'coil', 'coin', 'coke', 'cola', 'cold', 'cole', 'come', 'cone',
        'conn', 'cook', 'cool', 'cope', 'copy', 'cord', 'core', 'cork', 'corn', 'cost', 'coup', 'cove', 'crap', 'crew',
        'crop', 'crow', 'cube', 'cult', 'curb', 'cure', 'cute', 'dale', 'dame', 'damn', 'damp', 'dare', 'dark', 'dash',
        'data', 'date', 'dawn', 'days', 'dead', 'deaf', 'deal', 'dean', 'dear', 'debt', 'deck', 'deed', 'deep', 'deer',
        'dell', 'demo', 'dent', 'deny', 'desk', 'dial', 'dice', 'dick', 'diet', 'dire', 'dirt', 'disc', 'dish', 'disk',
        'dive', 'dock', 'does', 'dole', 'doll', 'dome', 'done', 'doom', 'door', 'dose', 'dove', 'down', 'drag', 'draw',
        'drew', 'drop', 'drug', 'drum', 'dual', 'duck', 'duff', 'duke', 'dull', 'duly', 'dumb', 'dump', 'dusk', 'dust',
        'duty', 'each', 'earl', 'earn', 'ease', 'east', 'easy', 'eats', 'echo', 'edge', 'edit', 'else', 'envy', 'epic',
        'euro', 'even', 'ever', 'evil', 'exam', 'exit', 'expo', 'eyed', 'face', 'fact', 'fade', 'fail', 'fair', 'fake',
        'fall', 'fame', 'fare', 'farm', 'fast', 'fate', 'fear', 'feat', 'feed', 'feel', 'feet', 'fell', 'felt', 'file',
        'fill', 'film', 'find', 'fine', 'fire', 'firm', 'fish', 'fist', 'five', 'flag', 'flat', 'fled', 'flee', 'flew',
        'flex', 'flip', 'flow', 'flux', 'foam', 'foil', 'fold', 'folk', 'fond', 'font', 'food', 'fool', 'foot', 'ford',
        'fore', 'fork', 'form', 'fort', 'foul', 'four', 'free', 'frog', 'from', 'fuck', 'fuel', 'full', 'fund', 'fury',
        'fuse', 'fuss', 'gain', 'gala', 'gale', 'gall', 'game', 'gang', 'gate', 'gave', 'gaze', 'gear', 'gene', 'gift',
        'gill', 'girl', 'give', 'glad', 'glen', 'glow', 'glue', 'goal', 'goat', 'goes', 'gold', 'golf', 'gone', 'good',
        'gore', 'gown', 'grab', 'gram', 'gray', 'grew', 'grey', 'grid', 'grim', 'grin', 'grip', 'grow', 'gulf', 'guru',
        'hail', 'hair', 'hale', 'half', 'hall', 'halt', 'hand', 'hang', 'hank', 'hard', 'harm', 'hart', 'hate', 'haul',
        'have', 'hawk', 'head', 'heal', 'heap', 'hear', 'heat', 'heel', 'heir', 'held', 'hell', 'helm', 'help', 'herb',
        'herd', 'here', 'hero', 'hers', 'hide', 'high', 'hike', 'hill', 'hint', 'hire', 'hold', 'hole', 'holt', 'holy',
        'home', 'hood', 'hook', 'hope', 'horn', 'hose', 'host', 'hour', 'huge', 'hull', 'hung', 'hunt', 'hurt', 'hype',
        'icon', 'idea', 'idle', 'idol', 'inch', 'info', 'into', 'iris', 'iron', 'isle', 'item', 'jack', 'jail', 'jake',
        'jane', 'java', 'jazz', 'jean', 'jeep', 'jill', 'joey', 'john', 'join', 'joke', 'josh', 'jump', 'junk', 'jury',
        'just', 'keen', 'keep', 'kemp', 'kent', 'kept', 'khan', 'kick', 'kill', 'kind', 'king', 'kirk', 'kiss', 'kite',
        'knee', 'knew', 'knit', 'knot', 'know', 'kohl', 'Kyle', 'lace', 'lack', 'lady', 'laid', 'lake', 'lamb', 'lamp',
        'land', 'lane', 'lang', 'last', 'late', 'lava', 'lawn', 'lazy', 'lead', 'leaf', 'leak', 'lean', 'leap', 'left',
        'lend', 'lens', 'lent', 'less', 'lest', 'levy', 'lied', 'lien', 'life', 'lift']
medium = ['better', 'beyond', 'bishop', 'border', 'bottle', 'bottom', 'bought', 'branch', 'breath', 'bridge', 'bright',
          'broken', 'budget', 'burden', 'bureau', 'button', 'camera', 'cancer', 'cannot', 'carbon', 'career', 'castle',
          'casual', 'caught', 'center', 'centre', 'chance', 'change', 'charge', 'choice', 'choose', 'chosen', 'church',
          'circle', 'client', 'closed', 'closer', 'coffee', 'column', 'combat', 'coming', 'common', 'comply', 'copper',
          'corner', 'costly', 'county', 'couple', 'course', 'covers', 'create', 'credit', 'crisis', 'custom', 'damage',
          'danger', 'dealer', 'debate', 'decade', 'decide', 'defeat', 'defend', 'define', 'degree', 'demand', 'depend',
          'deputy', 'desert', 'design', 'desire', 'detail', 'detect', 'device', 'differ', 'dinner', 'direct', 'doctor',
          'dollar', 'domain', 'double', 'driven', 'driver', 'during', 'easily', 'eating', 'editor', 'effect', 'effort',
          'eighth', 'either', 'eleven', 'emerge', 'empire', 'employ', 'enable', 'ending', 'energy', 'engage', 'engine',
          'enough', 'ensure', 'entire', 'entity', 'equity', 'escape', 'estate', 'ethnic', 'exceed', 'except', 'excess',
          'expand', 'expect', 'expert', 'export', 'extend', 'extent', 'fabric', 'facing', 'factor', 'failed', 'fairly',
          'fallen', 'family', 'famous', 'father', 'fellow', 'female', 'figure', 'filing', 'finger', 'finish', 'fiscal',
          'flight', 'flying', 'follow', 'forced', 'forest', 'forget', 'formal', 'format', 'former', 'foster', 'fought',
          'fourth', 'french', 'friend', 'future', 'garden', 'gather', 'gender', 'german', 'global', 'golden', 'ground',
          'growth', 'guilty', 'handed', 'handle', 'happen', 'hardly', 'headed', 'health', 'height', 'hidden', 'holder',
          'honest', 'impact', 'import', 'income', 'indeed', 'injury', 'inside', 'intend', 'intent', 'invest', 'island',
          'itself', 'jersey', 'joseph', 'junior', 'killed', 'labour', 'latest', 'latter', 'launch', 'lawyer', 'leader',
          'league', 'leaves', 'legacy', 'length', 'lesson', 'letter', 'lights', 'likely', 'linked', 'liquid', 'listen',
          'little', 'living', 'losing', 'lucent', 'luxury', 'mainly', 'making', 'manage', 'manner', 'manual', 'margin',
          'marine', 'marked', 'market', 'martin', 'master', 'matter', 'mature', 'medium', 'member', 'memory', 'mental',
          'merely', 'merger', 'method', 'middle', 'miller', 'mining', 'minute', 'mirror', 'mobile', 'modern', 'modest',
          'module', 'moment', 'morris', 'mostly', 'mother', 'motion', 'moving', 'murder', 'museum', 'mutual', 'myself',
          'narrow', 'nation', 'native', 'nature', 'nearby', 'nearly', 'nights', 'nobody', 'normal', 'notice', 'notion',
          'number', 'object', 'obtain', 'office', 'offset', 'online', 'option', 'orange', 'origin', 'output', 'oxford',
          'packed', 'palace', 'parent', 'partly', 'patent', 'people', 'period', 'permit', 'person', 'phrase', 'picked',
          'planet', 'player', 'please', 'plenty', 'pocket', 'police', 'policy', 'prefer', 'pretty', 'prince', 'prison',
          'profit', 'proper', 'proven', 'public', 'pursue', 'raised', 'random', 'rarely', 'rather', 'rating', 'reader',
          'really', 'reason', 'recall', 'recent', 'record', 'reduce', 'reform', 'regard', 'regime', 'region', 'relate',
          'relief', 'remain', 'remote', 'remove', 'repair', 'repeat', 'replay', 'report', 'rescue', 'resort', 'result',
          'retail', 'retain', 'return', 'reveal', 'review', 'reward', 'riding', 'rising', 'robust', 'ruling', 'safety',
          'salary', 'sample', 'saving', 'saying', 'scheme', 'school', 'screen', 'search', 'season', 'second', 'secret',
          'sector', 'secure', 'seeing', 'select', 'seller', 'senior', 'series', 'server', 'settle', 'severe', 'sexual',
          'should', 'signal', 'signed', 'silent', 'silver', 'simple', 'simply', 'single', 'sister', 'slight', 'smooth',
          'social', 'solely', 'sought', 'source', 'soviet', 'speech', 'spirit', 'spoken', 'spread', 'spring', 'square',
          'stable', 'status', 'steady', 'stolen', 'strain', 'stream', 'street', 'stress', 'strict', 'strike', 'string',
          'strong', 'struck', 'studio', 'submit', 'sudden', 'suffer', 'summer', 'summit', 'supply', 'surely', 'survey',
          'switch', 'symbol', 'system', 'taking', 'talent', 'target', 'taught', 'tenant', 'tender', 'tennis', 'thanks',
          'theory', 'thirty', 'though', 'threat', 'thrown', 'ticket', 'timely', 'timing', 'tissue', 'toward', 'travel',
          'treaty', 'trying', 'twelve', 'twenty', 'unable', 'unique', 'united', 'unless', 'unlike', 'update', 'useful',
          'valley', 'varied', 'vendor', 'versus', 'victim', 'vision', 'visual', 'volume', 'walker', 'wealth', 'weekly',
          'weight', 'wholly', 'window', 'winner', 'winter', 'within', 'wonder', 'worker', 'wright', 'writer', 'yellow']
hard = ['ashirwad', 'abashment', 'abdominal', 'abilities', 'abjection', 'abruption', 'absconded', 'absorbent',
        'absorbing', 'abundance', 'accepting', 'accession', 'accidence', 'accompany', 'accordant', 'according',
        'accretion', 'acetylate', 'acetylene', 'achieving', 'bacillary', 'backbiter', 'backcloth', 'backfield',
        'backhouse', 'backplate', 'backslide', 'backspace', 'backstage', 'backstair', 'backtrack', 'backwater',
        'backwoods', 'bacterial', 'badminton', 'ballerina', 'ballpoint', 'balzacian', 'bandstand', 'bandwidth',
        'cabdriver', 'calculate', 'caldarium', 'calibrate', 'calicular', 'caliphate', 'calligram', 'calvinist',
        'camarilla', 'cambridge', 'camcorder', 'camembert', 'canceling', 'candidate', 'canebrake', 'canonical',
        'cantering', 'capacitor', 'capillary', 'capricorn', 'danceable', 'dandelion', 'dangerous', 'dardanian',
        'daredevil', 'darkening', 'dashboard', 'dayspring', 'deadening', 'deadlight', 'deathless', 'debatable',
        'debaucher', 'decadence', 'decalogue', 'decameter', 'deception', 'deceptive', 'deciduous', 'deciliter',
        'eagerness', 'earliness', 'earnestly', 'earthling', 'earthstar', 'earthward', 'earthwork', 'earthworm',
        'easterner', 'easygoing', 'eccentric', 'eclipsing', 'ecologist', 'economics', 'economism', 'economist',
        'ecosystem', 'editorial', 'educating', 'education', 'fabricate', 'facecloth', 'faceplate', 'facetious',
        'facsimile', 'factional', 'factorial', 'factoring', 'factually', 'faculties', 'faddiness', 'fadedness',
        'faintness', 'fairyland', 'faithless', 'following', 'falsehood', 'falseness', 'falsified', 'falsifier',
        'gabardine', 'gagwriter', 'gainfully', 'galactose', 'galantine', 'galatians', 'galbraith', 'galeopsis',
        'galilaean', 'galingale', 'gallamine', 'gallantly', 'gallberry', 'gallstone', 'galvanism', 'galvanize',
        'galveston', 'galwegian', 'gameboard', 'garbology', 'habenaria', 'habitable', 'habituate', 'hackamore',
        'hackneyed', 'hadrosaur', 'haecceity', 'hailstone', 'hailstorm', 'hairbrush', 'hairiness', 'hairstyle',
        'halfpenny', 'halftrack', 'halitosis', 'halloween', 'hallowing', 'hallowmas', 'hallstand', 'halophile',
        'ibuprofen', 'icelander', 'identical', 'idiomatic', 'idiophone', 'idolizing', 'ignoramus', 'ignorance',
        'ikhanaton', 'illegible', 'illogical', 'imaginary', 'imagining', 'imbricate', 'imitation', 'immediate',
        'immensely', 'immensity', 'immersion', 'immigrant', 'jabbering', 'jacaranda', 'jackfruit', 'jackknife',
        'jacklight', 'jacksmelt', 'jacksnipe', 'jacksonia', 'jackstone', 'jackstraw', 'jacobinic', 'jacquerie',
        'jacquinia', 'jactation', 'jadedness', 'jadestone', 'jagannath', 'jagganath', 'jailbreak', 'jailhouse',
        'leviathan', 'levigator', 'leviticus', 'lexington', 'liability', 'liberally', 'liberated', 'liberator',
        'liberties', 'libertine', 'librarian', 'libration', 'lickerish', 'lidocaine', 'lifeblood', 'lifesaver',
        'mellowing', 'melodious', 'memorable', 'menagerie', 'mendacity', 'mendicant', 'mennonite', 'menopause',
        'mentalist', 'mentality', 'mentation', 'mercenary', 'merciless', 'mercurial', 'merriment', 'mescaline',
        'mesmerize', 'mesomorph', 'messaging', 'messalina', 'messenger', 'messiness', 'metabolic', 'metalloid',
        'metaphase', 'meteorite', 'metronome', 'metycaine', 'mezzanine', 'michelson', 'nidularia', 'nietzsche',
        'nightbird', 'nightclub', 'nightfall', 'nightgown', 'nighthawk', 'nighttide', 'nighttime', 'nightwalk',
        'nightwear', 'ninepence', 'ninetieth', 'ninhursag', 'nippiness', 'nipponese', 'nitpicker', 'nitration',
        'nitrospan', 'nobleness', 'nocturnal', 'noiseless', 'noisiness', 'noncausal', 'outsource', 'outspoken',
        'outwardly', 'overacted', 'overawing', 'overboard', 'overborne', 'overcomer', 'overdoing', 'overdraft',
        'overdrawn', 'overdress', 'overdrive', 'overeager', 'overgrown', 'overjoyed', 'overlying', 'overmatch',
        'overnight', 'overpoise', 'polyester', 'pondering', 'porcelain', 'porcupine', 'porphyria', 'portfolio',
        'portulaca', 'posterity', 'postulate', 'posturing', 'potentate', 'potential', 'potholder', 'powerless',
        'practical', 'prankster', 'preaching', 'preakness', 'precipice', 'precision', 'quicklime', 'quickness',
        'quicksand', 'quickstep', 'quiescent', 'quietener', 'quietness', 'quillwort', 'quindecim', 'quinidine',
        'quintuple', 'quiscalus', 'relatives', 'releasing', 'relevance', 'relieving', 'religious', 'relishing',
        'reluctant', 'remainder', 'remaining', 'remanding', 'remigrate', 'remington', 'remission', 'remittent',
        'renascent', 'rendering', 'rendition', 'renewable', 'renovated', 'renovator', 'repairing', 'repairman',
        'reparable', 'repayment', 'repeating', 'repellent', 'repentant', 'replacing', 'replaying', 'replenish',
        'snitching', 'sniveling', 'snowflake', 'snowstorm', 'snuffling', 'snuggling', 'socialism', 'socialist',
        'socialite', 'sociology', 'sociopath', 'solemness', 'solicitor', 'solipsism', 'solitaire', 'solvation',
        'something', 'sometimes', 'somnolent', 'sophomore', 'sorceress', 'soundness', 'sourdough', 'southwest',
        'sovereign', 'spaceship', 'spaghetti', 'termagant', 'terminate', 'terrarium', 'terrorism', 'terrorist',
        'terseness', 'testimony', 'texarkana', 'thankless', 'theatrics', 'theocracy', 'theophany', 'theravada',
        'thereupon', 'thermally', 'thesaurus', 'thickener', 'thickness', 'thighbone', 'thinkable', 'thirstily',
        'thirsting', 'thirtieth', 'thornless', 'thousands', 'thrashing', 'threatful', 'threshing', 'threshold',
        'thrilling', 'throbbing', 'thronging', 'throttler', 'throwback', 'thrumming', 'thrusting', 'thumbtack',
        'thuringia', 'thwarting', 'thylacine', 'thyronine', 'thyroxine', 'tidewater', 'tightness', 'tightrope',
        'timberman', 'timetable', 'timidness', 'tinkering', 'tipsiness', 'tiptoeing', 'tiredness', 'toadstool',
        'unreeling', 'unrefined', 'unrefuted', 'unregular', 'unrelated', 'unrivaled', 'unrolling', 'unrooting',
        'unruffled', 'unsalable', 'unseating', 'unselfish', 'unserious', 'unsettled', 'unsightly', 'unsimilar',
        'unskilled', 'unsmiling', 'unsounded', 'unsparing', 'unspoiled', 'unsuccess', 'untactful', 'untainted',
        'untangled', 'vergeress', 'veridical', 'verifying', 'veritable', 'veritably', 'vermicide', 'vermiform',
        'vermifuge', 'vermilion', 'verminous', 'vermonter', 'vernation', 'verrazano', 'verrucose', 'versatile',
        'versifier', 'vertebrae', 'vertebral', 'vesicaria', 'vesicated', 'vesicular', 'vespasian', 'vestibule',
        'vestigial', 'vestryman', 'vetchling', 'vetturino', 'vexatious', 'watchword', 'waterbird', 'waterbury',
        'waterfall', 'waterford', 'waterfowl', 'watergate', 'waterless', 'waterline', 'watermark', 'watermeal',
        'watershed', 'waterside', 'watertown', 'waterweed', 'wayfaring', 'weakening', 'wealthily', 'weaponize',
        'weariless', 'weariness', 'wearisome', 'weathered']


def getEasy():
    global easy
    return easy


def getMedium():
    global medium
    return medium


def getHard():
    global hard
    return hard
